backend:
  name: github
  repo: daichi-amano/yaad
  branch: master
  site_domain: "yaad-gold.vercel.app"
  base_url: "https://yaad-gold.vercel.app"
  auth_endpoint: "/api/auth"
media_folder: "src/assets/images"
public_folder: "../assets/images"
collections:
  - name: works
    label: Works
    label_singular: Work
    folder: "src/pages"
    extension: "md"
    format: frontmatter
    identifier_field: id
    create: true
    slug: "{{id}}"
    summary: "{{id}} - {{title}}"
    sortable_fields: ["id", "title", "release"]
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: "../layouts/ContentLayout.astro"
      - label: ID
        name: id
        widget: string
        required: true
        pattern: ['^[^/\\\\]+$', "スラッシュやバックスラッシュは使用できません"]
        hint: "このIDがファイル名として使用されます。既存のIDと重複しないようにしてください。IDを変更すると、ファイル名も変更されます。"
      - label: Title
        name: title
        widget: string
        required: true
      - label: Image
        name: img
        widget: image
        required: true
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Client
        name: client
        widget: string
        required: true
      - label: Release
        name: release
        widget: string
        required: false
      - label: Categories
        name: categories
        widget: list
        field:
          label: Category
          name: category
          widget: string
        required: false
      - label: Credits
        name: credits
        widget: list
        collapsed: true
        fields:
          - label: Role
            name: name
            widget: string
          - label: Values
            name: value
            widget: list
            field:
              label: Value
              name: value
              widget: string
        required: false
