backend:
  name: github
  repo: daichi-amano/yaad
  branch: master
  site_domain: "yaad.tokyo"
  base_url: "https://yaad.tokyo"
  auth_endpoint: "/api/auth"
media_folder: "src/assets/images"
public_folder: "../assets/images"
collections:
  - name: works
    label: Works
    label_singular: Work
    folder: "src/pages"
    extension: "md"
    format: frontmatter
    identifier_field: id
    create: true
    slug: "{{id}}"
    summary: "{{id}} - {{title}}"
    sortable_fields: ["id", "title", "release"]
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: "../layouts/ContentLayout.astro"
      - label: ID
        name: id
        widget: string
        hint: "https://yaad.tokyo/{id} の形式でURLが生成されます。一度保存したIDは変更してもURLには反映されません。他のコンテンツと同一IDは使用しないでください。"
        pattern:
          - "^[a-z0-9-]+$"
          - "半角英数字小文字とハイフンのみ"
      - label: Title
        name: title
        widget: string
        required: true
      - label: Image
        name: img
        widget: image
        required: true
      - label: SubImages
        name: subImages
        widget: list
        required: false
        field:
          label: Image
          name: img
          widget: image
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Client
        name: client
        widget: string
        required: false
      - label: Release
        name: release
        widget: string
      - label: Categories
        name: categories
        widget: list
        field:
          label: Category
          name: category
          widget: string
      - label: Credits
        name: credits
        widget: list
        collapsed: true
        fields:
          - label: Role
            name: name
            widget: string
          - label: Values
            name: value
            widget: list
            field:
              label: Value
              name: value
              widget: string
